version: '3.7'

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: dockerFile
    volumes:
      - ".:/app"
    ports:
      - "9000:3000" # 외부:내부
    environment:
      - NODE_ENV=development
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/dockerFile
